#!/usr/bin/ruby

require 'fileutils'
require 'mysql'
require File.dirname(__FILE__) + '/utility.rb'

cafetool_dir, path_config = Utility.initial(__FILE__)
workspace = path_config['workspace:']
cafedir = path_config['cafegrader:']
sqlgrader = SqlGrader.new(cafedir)
list = sqlgrader.list_problem
complete_problem = Dir[workspace + '/complete/*']
complete_problem.each do |file|
	problem = File.basename(file, '.*')
	list.delete(problem)
end
liststr = '"' + list * '" "' + '"'
selected = `zenity --title="Select problem" --width="300" \
--height="400" --list --text "Select problem : " --hide-header \
--column="" #{liststr}`
selected.chomp!
abort('Abort !') if selected == ""
source_file = "#{workspace}/#{selected}.cpp"
if !FileTest.exist?(source_file)
	fp = File.new(source_file, 'w')
	fp.puts "/*"
	fp.puts "TASK: #{selected}"
	fp.puts "LANG: C++"
	fp.puts "*/"
	fp.puts
	fp.puts "#include <cstdio>"
	fp.puts
	fp.puts "int main(){"
	fp.puts
	fp.puts "	return 0;"
	fp.puts "}"
	fp.close
end

id = sqlgrader.find_id(selected)
sqlgrader.close
`acroread #{cafedir}/web/data/tasks/#{id}/#{selected}.pdf &`
`geany #{source_file} > /dev/null &`
