#!/usr/bin/ruby

require 'fileutils'

def rmempty(name)
	if FileTest.directory?(name)
		exit(0)
	end
	fp = File.new(name,"r")
	set = fp.read.split
	fp.close
	code = ""
	set.each do |s|
		code << "#{s} "
	end
	if code =~ /#include <cstdio> int main\(\)\{ return 0; \}/
		FileUtils.rm(name)
	end
end


current_dir = File.expand_path("~") + "/cafe_grader/cafetool"
system("geany #{current_dir}/data/availprob");
workspace_fp = File.new(current_dir + "/config/workspace")
workspace_path = workspace_fp.readline
workspace_fp.close
workspace_path = workspace_path.chomp
sources = Dir[workspace_path + '/*']
sources.each do |s|
	rmempty(s)
end
