#!/usr/bin/ruby

require 'fileutils'
require File.dirname(__FILE__) + '/utility.rb'

def rmempty(name)
	return if FileTest.directory?(name)
	set = Utility.readfile(name).split
	code = ""
	set.each do |s|
		code << "#{s} "
	end
	if code =~ /#include <cstdio> int main\(\)\{ return 0; \}/
		FileUtils.rm(name)
	end
end

########################################################################

cafetool_dir, path_config = Utility.initial(__FILE__)
`geany`
sources = Dir[info_config["workspace:"] + '/*']
sources.each do |s|
	rmempty(s)
end
