#!/usr/bin/ruby

require 'fileutils'
require File.dirname(__FILE__) + '/../script/graderutils.rb'

cafetool_dir, path_config = GraderUtils.initial(__FILE__)
geany_dir = File.expand_path('~/.config/geany')

# keybindings.conf
conf = geany_dir + '/keybindings.conf'
FileUtils.cp(conf, geany_dir + '/keybindings.conf.backup') \
if FileTest.exist?(conf)
data = GraderUtils.readfile(conf)
fp = File.new(conf, 'w')
lis = ["\[Bindings\]", "build_compile=", "build_link=", "build_make=",
"build_makeowntarget=", "build_makeobject="]
val = ['', 'F3', 'F9', 'F8', '', 'F10']
if data != nil
	data.each_line do |line|
		flag = true
		for i in 0 ... lis.length
			if line =~ /^#{lis[i]}/
				fp.puts "#{lis[i]}#{val[i]}"
				flag = false
				break
			end
		end
		fp.puts line if flag
	end
else
	for i in 0 ... lis.length
		fp.puts "#{lis[i]}#{val[i]}"
	end
end
fp.close

# geany.conf
conf = geany_dir + '/geany.conf'
FileUtils.cp(conf, geany_dir + '/geany.conf.backup') \
if FileTest.exist?(conf)
data = GraderUtils.readfile(conf)
fp = File.new(conf, 'w')
data.each_line do |line|
	next if line =~ /^NF_/ || line =~ /^\[build-menu\]/
	fp.puts line
end if data != nil
fp.puts "[build-menu]"
fp.puts "NF_00_LB=_Terminal"
fp.puts "NF_00_CM=gnome-terminal &"
fp.puts "NF_00_WD="
fp.puts "NF_01_LB="
fp.puts "NF_01_CM="
fp.puts "NF_01_WD="
fp.puts "NF_02_LB=_Search Problem"
fp.puts "NF_02_CM=./search_prob"
fp.puts "NF_02_WD=#{cafetool_dir}/script"
fp.puts "NF_03_LB="
fp.puts "NF_03_CM="
fp.puts "NF_03_WD="
fp.close

# C++
conf = geany_dir + '/filedefs/filetypes.cpp'
FileUtils.cp(conf, geany_dir + '/filedefs/filetypes.cpp.backup') \
if FileTest.exist?(conf)
data = GraderUtils.readfile(conf)
fp = File.new(conf, 'w')
data.each_line do |line|
	next if line =~ /^FT_/ || line =~ /^\[build-menu\]/
	fp.puts line
end if data != nil
fp.puts "[build-menu]"
fp.puts "FT_00_LB=_Build"
fp.puts "FT_00_CM=g++ -Wall -o \"%e\" \"%f\""
fp.puts "FT_00_WD="
fp.puts "FT_01_LB=_Cafetool"
fp.puts "FT_01_CM=./cafetool_geany \"%f\""
fp.puts "FT_01_WD=#{cafetool_dir}/geany"
fp.puts "FT_02_LB="
fp.puts "FT_02_CM="
fp.puts "FT_02_WD="
fp.close
